"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { Check, Download, Loader2, LockKeyhole, Save } from "lucide-react";
import { supabaseBrowser } from "@/lib/supabase-browser";
import { modelCampaign } from "@/lib/campaign-model";

const money = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 });
const verticals = ["General B2B", "SaaS", "Cybersecurity", "Fintech", "Medtech", "Industrial / IoT", "Telecom", "CRM", "Adtech", "Insurance tech"];
export default function ReportBuilder() {
  const [token, setToken] = useState<string | null>(null); const [pro, setPro] = useState<boolean | null>(null); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null);
  const [name, setName] = useState("Q3 AI Summit"); const [organization, setOrganization] = useState("Your organization"); const [vertical, setVertical] = useState("General B2B"); const [primary, setPrimary] = useState("#071529"); const [accent, setAccent] = useState("#b5ff32"); const [narrative, setNarrative] = useState("This campaign created measurable commercial momentum within the 90-day reporting window while preserving the full opportunity context for longer-cycle deals.");
  const [metrics, setMetrics] = useState({ spend: 42000, opportunities: 28, averageDealValue: 28000, salesCycleDays: 120 });
  const result = useMemo(() => modelCampaign({ source: "report_builder", external_id: name.toLowerCase().replace(/\W+/g,"-"), name, spend: metrics.spend, opportunities: metrics.opportunities, average_deal_value: metrics.averageDealValue, sales_cycle_days: metrics.salesCycleDays }), [metrics, name]);
  const headers = () => ({ authorization: `Bearer ${token}`, "content-type": "application/json" });
  useEffect(() => { const client = supabaseBrowser(); if (!client) { setPro(false); return; } void client.auth.getSession().then(async ({ data }) => { const access = data.session?.access_token ?? null; setToken(access); if (!access) { setPro(false); return; } const response = await fetch("/api/entitlement", { headers: { authorization: `Bearer ${access}` } }); const payload = await response.json() as { pro?: boolean }; setPro(Boolean(payload.pro)); }); }, []);
  async function checkout() { if (!token) { window.location.assign("/account?return_to=/toolkit"); return; } setBusy(true); const response = await fetch("/api/checkout", { method: "POST", headers: headers() }); const data = await response.json() as { url?: string; error?: string }; if (data.url) window.location.assign(data.url); else { setMessage(data.error ?? "Checkout is not configured yet."); setBusy(false); } }
  async function save() { setBusy(true); setMessage(null); const response = await fetch("/api/reports", { method: "POST", headers: headers(), body: JSON.stringify({ name, vertical: vertical.toLowerCase().replace(/\W+/g,"_"), organization_name: organization, primary_color: primary, accent_color: accent, narrative, report_data: { ...metrics, result } }) }); const data = await response.json() as { error?: string }; setMessage(response.ok ? "Report saved to campaign history." : data.error ?? "Report could not be saved."); setBusy(false); }
  if (pro === null) return <div className="empty-state"><Loader2 className="animate-spin"/><p>Checking your workspace access…</p></div>;
  if (!pro) return <div className="paywall-card"><LockKeyhole size={28}/><p className="kicker">Campaign Proof Pro</p><h2>Unlock the complete report toolkit.</h2><p>Build branded PDFs, apply vertical benchmarks, save campaign history, reveal the complete methodology, and optionally import CRM data.</p><ul>{["Industry-specific vertical scoring","Branded, editable PDF reports","Saved reports and campaign history","Full methodology and source audit trail","HubSpot, Salesforce, and API imports"].map((item)=><li key={item}><Check size={15}/>{item}</li>)}</ul><div className="paywall-price"><strong>$39</strong><span>/ month</span></div><button className="button" onClick={() => void checkout()} disabled={busy}>{busy && <Loader2 className="animate-spin" size={16}/>}Upgrade to Pro</button>{message && <p className="message message-error">{message}</p>}<Link href="/#calculator">Return to the free calculator</Link></div>;
  return <div className="report-studio"><aside className="report-controls"><p className="kicker">Report settings</p><label>Report name<input value={name} onChange={(e)=>setName(e.target.value)}/></label><label>Organization<input value={organization} onChange={(e)=>setOrganization(e.target.value)}/></label><label>Vertical<select value={vertical} onChange={(e)=>setVertical(e.target.value)}>{verticals.map((item)=><option key={item}>{item}</option>)}</select></label><div className="color-row"><label>Primary<input type="color" value={primary} onChange={(e)=>setPrimary(e.target.value)}/></label><label>Accent<input type="color" value={accent} onChange={(e)=>setAccent(e.target.value)}/></label></div><label>Campaign cost<input type="number" value={metrics.spend} onChange={(e)=>setMetrics({...metrics,spend:Number(e.target.value)})}/></label><label>Opportunities<input type="number" value={metrics.opportunities} onChange={(e)=>setMetrics({...metrics,opportunities:Number(e.target.value)})}/></label><label>Average deal value<input type="number" value={metrics.averageDealValue} onChange={(e)=>setMetrics({...metrics,averageDealValue:Number(e.target.value)})}/></label><label>Deal cycle (days)<input type="number" value={metrics.salesCycleDays} onChange={(e)=>setMetrics({...metrics,salesCycleDays:Number(e.target.value)})}/></label><label>Executive narrative<textarea rows={7} value={narrative} onChange={(e)=>setNarrative(e.target.value)}/></label><div className="studio-actions"><button className="button" disabled={busy} onClick={() => void save()}><Save size={15}/>Save report</button><button className="button button-secondary" onClick={()=>window.print()}><Download size={15}/>Export PDF</button></div>{message && <p className="message">{message}</p>}</aside><article className="report-preview" style={{"--report-primary":primary,"--report-accent":accent} as React.CSSProperties}><header><span className="report-logo">CP↗</span><div><strong>{organization}</strong><span>Campaign performance report</span></div></header><p className="kicker">{vertical} benchmark view</p><h1>{name}</h1><div className="report-hero-metric"><span>90-day attributable value</span><strong>{money.format(result.attributable_value)}</strong><small>{result.modeled_roi?.toFixed(1)}× modeled ROI</small></div><p className="report-narrative">{narrative}</p><div className="report-grid"><div><span>Investment</span><strong>{money.format(metrics.spend)}</strong></div><div><span>Opportunity value</span><strong>{money.format(result.modeled_opportunity_value)}</strong></div><div><span>Cycle adjustment</span><strong>{Math.round(Math.min(90/Math.max(metrics.salesCycleDays,1),1)*100)}%</strong></div><div><span>Opportunities</span><strong>{metrics.opportunities}</strong></div></div><footer><span>Methodology {result.methodology_version}</span><span>Benchmark b2b-2026.09</span><span>90-day window</span></footer></article></div>;
}
